project_id = "krtnihxiiapvkudpehoj"

[functions.send-to-rdstation]
verify_jwt = false

[functions.send-to-meta-capi]
verify_jwt = false

[functions.send-to-google-sheets]
verify_jwt = false

[functions.save-lead]
verify_jwt = false

[functions.rebuild-sheet]
verify_jwt = false
